spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringAuth
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  security:
    jwt:
      secret-key: wiHpgJV9Is0zQRcsQYuOfVblNxfXkU4z6JquCyd4INV
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days